const fs = require('fs');
const path = require('path');

const baseUrl = 'https://ivanwalsh.com';
const blogDir = path.resolve(__dirname, '../blog');
const outputFile = path.resolve(__dirname, '../static/llm.txt');

const frontmatterRegex = /^---\s*([\s\S]*?)\s*---/;
const fieldRegex = /^(\w+):\s*(.+)$/gm;

function parseFrontmatter(content) {
  const match = content.match(frontmatterRegex);
  if (!match) return {};
  const frontmatter = match[1];
  const result = {};
  let fieldMatch;
  while ((fieldMatch = fieldRegex.exec(frontmatter)) !== null) {
    const key = fieldMatch[1].trim();
    let value = fieldMatch[2].trim();
    if (value.startsWith('[') && value.endsWith(']')) {
      value = value.slice(1, -1).split(',').map((item) => item.trim().replace(/^\[|\]$/g, ''));
    }
    result[key] = value;
  }
  return result;
}

function normalizeSlug(slug, filename) {
  if (slug) {
    return slug.replace(/^\/+/, '').replace(/\/+$|\.md$/g, '');
  }
  return filename.replace(/\.md$/, '').replace(/^\d{4}-\d{2}-\d{2}-/, '');
}

function slugToUrl(slug) {
  return `${baseUrl}/blog/${slug}`;
}

function formatListItem(text, url) {
  return `- ${text}: ${url}`;
}

function buildText(posts) {
  const lines = [
    '# Ivan Walsh Technical Documentation',
    '',
    '## About',
    '',
    'This file is served from the site root at /llm.txt. It is regenerated automatically from the blog metadata in the repository.',
    '',
    '## Main Links',
    '',
    formatListItem('Home', `${baseUrl}/`),
    formatListItem('Articles', `${baseUrl}/blog`),
    formatListItem('About Ivan', `${baseUrl}/Ivan`),
    formatListItem('Newsletter', `${baseUrl}/newsletter`),
    '',
    '## Latest Blog Posts',
    '',
  ];

  const postLines = posts.map((post) => formatListItem(post.title, post.url));
  if (postLines.length === 0) {
    lines.push('- No blog posts found.');
  } else {
    lines.push(...postLines);
  }

  lines.push('', '## Notes', '', 'This file is generated by scripts/generate-llm-txt.js.');
  return lines.join('\n');
}

function main() {
  const files = fs.readdirSync(blogDir, { withFileTypes: true });
  const posts = files
    .filter((file) => file.isFile() && file.name.endsWith('.md'))
    .map((file) => {
      const fullPath = path.join(blogDir, file.name);
      const content = fs.readFileSync(fullPath, 'utf8');
      const fm = parseFrontmatter(content);
      const title = fm.title || file.name.replace(/\.md$/, '').replace(/^\d{4}-\d{2}-\d{2}-/, '').replace(/-/g, ' ');
      const slug = normalizeSlug(fm.slug, file.name);
      const url = slugToUrl(slug);
      return {
        title,
        url,
        date: fm.date || file.name.slice(0, 10),
      };
    })
    .sort((a, b) => (a.date > b.date ? -1 : a.date < b.date ? 1 : 0));

  const text = buildText(posts);
  fs.writeFileSync(outputFile, text, 'utf8');
  console.log(`Generated ${path.relative(process.cwd(), outputFile)} with ${posts.length} blog posts.`);
}

main();
